---
#-------------------------------
# General Site Settings

title: Miaro
logo: assets/images/favicon.png
author: Miaro Fandresena
description: Boostez votre visibilité en ligne avec Miaro Fandresena, spécialiste en SEO, marketing digital.
email: miarofandresena@gmail.com
phone: +261 343388363
address: Sabotsy Namehana, Antananarivo, Madagascar
copyright: Copyright &copy; Miaro Fandresena 2025

menu:
  - { name: A propos, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
#  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! Je suis <br> Miaro Fandresena <br> Specialiste SEO

social:
  - { icon: "ti-facebook", link: "https://web.facebook.com/miarofandresena.rafanomezaniavo/" }
  - { icon: "ti-github", link: "https://github.com/miarofandresena/" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/miaro-fandresena-rafanomezaniavo-574208161/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Passionné par le Web, j'ai consacré les quatre dernières années à me spécialiser dans le référencement naturel (SEO). J'excelle dans la gestion de sites internet, de réseaux de sites et de sites e-commerce, en développant des stratégies de web-marketing adaptées aux besoins des entreprises.

blurb-btn-link: "/about"
blurb-btn-name: Apprendre plus sur moi

# About Page

# Work Process Section
# work-process:
#   - title: "Research and Plan"
#     icon: "assets/images/icons/plan.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Design and Develop"
#     icon: "assets/images/icons/design.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Deliver"
#     icon: "assets/images/icons/print.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# # My Team Section
# team:
#   - title: "Jack Schenziwe"
#     image: "assets/images/team/member-1.png"
#     designation: "Project Manager"

#   - title: "Julias Carlie"
#     image: "assets/images/team/member-2.png"
#     designation: "Web Developer"

#   - title: "John Doe"
#     image: "assets/images/team/member-3.png"
#     designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: SEO, color: "#fdb157", value: "90%" }
  - { name: WordPress, color: "#9473e6", value: "80%" }
  - { name: Marketing Digital, color: "#bdecf6", value: "50%" }
  - { name: Gestion de Projet Web, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-1.png",
      date: "Février 2024 - Maintenant",
      organization: "A mon compte",
    }
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-2.png",
      date: "Septembre 2020 - Février 2024",
      organization: "X-Com Agency",
    }
  - {
      name: "Développeur Web",
      icon: "icon-3.png",
      date: "Décembre 2019 - Janvier 2020",
      organization: "Cubicom",
    }
  - {
      name: "Développeur Web",
      icon: "icon-1.png",
      date: "Janvier 2019 - Juillet 2020",
      organization: "Wiclick",
    }
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Licence en Informatique,
      date: "2019",
      organization: "UPH",
    }
  - {
      name: "Diplôme de Technicien Supérieur",
      date: "2016",
      organization: "ISIME",
    }
  - {
      name: "Baccalauréat Série A2",
      date: "2015",
      organization: "LP Idéal",
    }
#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: "Optimisation SEO Avancée",
      icon: ti-palette,
      description: "Maximisez la visibilité de votre site internet grâce à des stratégies de référencement naturel personnalisées et adaptées à votre marché. Améliorez votre notoriété en ligne, attirez un flux constant de nouveaux clients et boostez votre retour sur investissement grâce à une optimisation SEO efficace 🚀",
      link: /seo,
      active: , # Add true to select section
    }
  - {
      name: "Gestion de Marketing Digital",
      icon: ti-vector,
      description: "Déployez une stratégie digitale efficace en combinant le référencement naturel (SEO), webmarketing et référencement payant (Google Ads, Facebook Ads). Améliorez la communication digitale de votre entreprise et développez votre image de marque sur le web.",
      link: /marketing,
      active: true, # Add true to select section
    }
  - {
      name: "Développement de Sites Web",
      icon: ti-panel,
      description: "Créez un site vitrine, e-commerce ou un site responsive performant et sécurisé. Nous développons des pages web optimisées pour le référencement et adaptées aux CMS comme WordPress et Prestashop, garantissant une expérience utilisateur optimale.",
      link: /web,
      active: , # Add true to select section
    }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-4.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Référencement Naturel", type: "referencement" }
  - { title: "Marketing Digital", type: "maketing" }
  - { title: "Gestion de site web", type: "web" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"
      - type: "web"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-6.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"

  - image: "assets/images/portfolio/item-8.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"
      - type: "referencement"

  - image: "assets/images/portfolio/item-7.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
faq-items:
  - id: 1
    icon: fa-question-circle
    question: Quels services proposez-vous ?
    answer: J'offre des services en SEO, webmarketing, stratégie digitale, gestion de projets numériques et développement web. Mon expertise inclut également la création de sites internet, le référencement payant et l'amélioration de l'ergonomie des pages web.
  - id: 2
    icon: fa-truck
    question: Comment pouvez-vous améliorer la visibilité de mon site sur Google ?
    answer: J'applique une stratégie de référencement naturel et payant optimisée, incluant l'optimisation des mots-clés, l'amélioration de l'ergonomie, la création de backlinks et l'optimisation des campagnes Google AdWords.
  - id: 3
    icon: fa-lock
    question: En quoi consiste l'assistanat virtuel et comment peut-il m'aider ?
    answer: L'assistanat virtuel inclut la gestion des tâches administratives, la gestion des campagnes mailing et l'organisation de stratégie de communication digitale, vous permettant de vous concentrer sur votre cœur de métier.
  - id: 4
    icon: fa-lock
    question: Quelle est votre approche pour la création de sites web ?
    answer: Je conçois des sites vitrine et e-commerce sur mesure, en utilisant des CMS comme WordPress et Prestashop. Chaque site est optimisé pour le SEO et conçu pour garantir une expérience utilisateur fluide et efficace.
  - id: 5
    icon: fa-lock
    question: Quels outils utilisez-vous pour le SEO et le marketing digital ?
    answer: J’utilise des outils comme Google Analytics, Google Search Console et des plateformes de publicité comme Google Ads pour une meilleure stratégie digitale et un retour sur investissement optimisé.
  - id: 6
    icon: fa-lock
    question: Avez-vous une expérience en gestion d'équipe ?
    answer: Oui, je gère une équipe spécialisée en SEO, rédaction de contenu, gestion de campagnes Adwords et développement web, afin d’assurer une exécution fluide des projets.
  - id: 7
    icon: fa-lock
    question: Quels types de projets avez-vous gérés ?
    answer: J'ai travaillé sur des projets de création de site web, refonte de sites internet, mise en place de stratégies de communication et optimisation du référencement payant et naturel.
  - id: 8
    icon: fa-lock
    question: Quels sont vos tarifs pour les services SEO et marketing digital ?
    answer: "Je propose des forfaits adaptés en fonction des besoins : création de site, SEO, stratégie digitale et publicité en ligne. Contactez-moi pour un devis personnalisé."
  - id: 9
    icon: fa-lock
    question: Pourquoi devrais-je choisir vos services ?
    answer: Mon approche repose sur une stratégie marketing complète, alliant référencement naturel, web-marketing et optimisation de l’expérience utilisateur, pour garantir une présence efficace sur le web.
  - id: 10
    icon: fa-lock
    question: Comment puis-je vous contacter ?
    answer: Vous pouvez me joindre via le <a href="/contact">formulaire de contact</a>, par email ou téléphone. Je suis disponible pour collaborer en télétravail ou en présentiel selon vos besoins.
#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: miarofandresena@gmail.com
contact-info : f/xblryjqd
