---
#-------------------------------
# General Site Settings

title: Miaro
logo: assets/images/favicon.png
author: Miaro Fandresena
description: Boostez votre visibilité en ligne avec Miaro Fandresena, spécialiste en SEO, marketing digital.
email: miarofandresena@gmail.com
phone: +261 343388363
address: Sabotsy Namehana, Antananarivo, Madagascar
copyright: Copyright &copy; Miaro Fandresena 2025

menu:
  - { name: A propos, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
#  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! Je suis <br> Miaro Fandresena <br> Specialiste SEO

social:
  - { icon: "ti-facebook", link: "https://web.facebook.com/miarofandresena.rafanomezaniavo/" }
  - { icon: "ti-github", link: "https://github.com/miarofandresena/" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/miaro-fandresena-rafanomezaniavo-574208161/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Passionné par le Web, j'ai consacré les quatre dernières années à me spécialiser dans le référencement naturel (SEO) et la création de site internet, optimisant le référencement d'un site pour une visibilité sur Internet. En tant que freelance et prestataire web, j'excelle dans la gestion de contenu et l’optimisation de votre site internet, collaborant avec des agences de communication, agences digitales, agences de création, agences internet et agences webdesign. Que ce soit pour la création de site, la refonte du site ou la réalisation d'un site internet, mon expertise en web-design, conception de site et stratégie marketing me permet de proposer des solutions web sur mesure, alliant ergonomie, design responsive, expérience utilisateur optimale et création graphique. Je transforme vos idées en réalisations concrètes sur le Web, en développant un site web innovant pour votre entreprise web, que ce soit un site vitrine, un intranet, un Ecommerce ou un nouveau site, avec un nom de domaine soigné et des templates modernes.

blurb-btn-link: "/about"
blurb-btn-name: Apprendre plus sur moi

# About Page

# Work Process Section
# work-process:
#   - title: "Research and Plan"
#     icon: "assets/images/icons/plan.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Design and Develop"
#     icon: "assets/images/icons/design.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Deliver"
#     icon: "assets/images/icons/print.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# # My Team Section
# team:
#   - title: "Jack Schenziwe"
#     image: "assets/images/team/member-1.png"
#     designation: "Project Manager"

#   - title: "Julias Carlie"
#     image: "assets/images/team/member-2.png"
#     designation: "Web Developer"

#   - title: "John Doe"
#     image: "assets/images/team/member-3.png"
#     designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: SEO, color: "#fdb157", value: "90%" }
  - { name: WordPress, color: "#9473e6", value: "80%" }
  - { name: Marketing Digital, color: "#bdecf6", value: "50%" }
  - { name: Gestion de Projet Web, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-1.png",
      date: "Février 2024 - Maintenant",
      organization: "A mon compte",
    }
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-2.png",
      date: "Septembre 2020 - Février 2024",
      organization: "X-Com Agency",
    }
  - {
      name: "Développeur Web",
      icon: "icon-3.png",
      date: "Décembre 2019 - Janvier 2020",
      organization: "Cubicom",
    }
  - {
      name: "Développeur Web",
      icon: "icon-1.png",
      date: "Janvier 2019 - Juillet 2020",
      organization: "Wiclick",
    }
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Licence en Informatique,
      date: "2019",
      organization: "UPH",
    }
  - {
      name: "Diplôme de Technicien Supérieur",
      date: "2016",
      organization: "ISIME",
    }
  - {
      name: "Baccalauréat Série A2",
      date: "2015",
      organization: "LP Idéal",
    }
#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: "Optimisation SEO Avancée",
      icon: ti-palette,
      description: "Maximisez la visibilité de votre site sur les moteurs de recherche grâce à des stratégies SEO personnalisées. En tant qu'agence digitale experte et prestataire web, nous optimisons le référencement de votre site tout en garantissant une expérience utilisateur optimale et des solutions web innovantes. Que ce soit pour la création de site, la création de site internet ou la création de sites internet, nous combinons design responsive, conception moderne et optimisation SEO pour sublimer votre présence en ligne. Nous collaborons avec des agences de création et de webdesign pour développer un site performant, attractif et adapté à votre entreprise, renforçant ainsi votre visibilité à long terme. Notre objectif est d'attirer des clients, améliorer votre visibilité et vous garantir le succès numérique. 🚀",
      link: /seo,
      active: , # Add true to select section
    }
  - {
      name: "Gestion de Marketing Digital",
      icon: ti-vector,
      description: "Déployez une stratégie digitale performante en combinant SEO, web-marketing et référencement payant (Google Ads, Facebook Ads). En tant qu'agence digitale et agence de communication, nous élaborons des stratégies marketing inbound et utilisons des templates modernes pour optimiser le référencement de votre site et votre communication web. Nos consultants mobilisent des solutions web innovantes et des supports digitaux pour améliorer l'expérience utilisateur de votre site internet et créer un nouveau site attractif. Nous collaborons avec des agences WordPress, agences de création et agences webdesign pour offrir à votre entreprise une visibilité optimale sur Internet. En intégrant des outils d'analyse et en suivant les tendances, nous garantissons une présence en ligne efficace.",
      link: /marketing,
      active: true, # Add true to select section
    }
  - {
      name: "Développement de Sites Web",
      icon: ti-panel,
      description: "Créez un site internet vitrine, e-commerce, intranet ou responsive, performant et sécurisé. Spécialisés en webdesign et création graphique, nous assurons la création de sites optimisés et professionnels avec un design responsive. Optez pour 'Créer un site internet' qui reflète votre identité digitale et garantit une expérience utilisateur optimale. Nos projets incluent des fonctionnalités e-commerce, intranet, applications mobiles et tablettes, avec un nom de domaine adapté. En tant qu'agence webdesign, nous réalisons des sites sur mesure avec des solutions digitales innovantes, templates modernes, Prestashop, Magento, Joomla et WordPress. Nous proposons aussi la refonte de sites pour moderniser votre image et créer un site attractif.",
      link: /web,
      active: , # Add true to select section
    }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-4.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Référencement Naturel", type: "referencement" }
  - { title: "Marketing Digital", type: "maketing" }
  - { title: "Gestion de site web", type: "web" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"
      - type: "web"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-6.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"

  - image: "assets/images/portfolio/item-8.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"
      - type: "referencement"

  - image: "assets/images/portfolio/item-7.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
faq-items:
  - id: 1
    icon: fa-question-circle
    question: Quels services proposez-vous ?
    answer: J'offre des services en SEO, webmarketing et stratégie digitale, incluant la création de site, la création de site internet, la conception de site Web et la réalisation d'un site internet. Je propose également le développement d'un site web, la refonte du site et l'optimisation du référencement d'un site. Mon expertise s'étend à la gestion de contenu, au développement du site et à la création graphique, en collaboration avec des agences de communication, agences digitales, agences de création, agences wordpress et agences internet. En tant que concepteur de site Web, je garantis une expérience utilisateur optimale grâce à des solutions web innovantes et des templates modernes.
  - id: 2
    icon: fa-truck
    question: Comment pouvez-vous améliorer la visibilité de mon site sur Google ?
    answer: J'applique une stratégie de référencement d'un site intégrant SEO et campagnes payantes, en optimisant l'expérience utilisateur avec un design responsive et en développant votre site internet via des solutions digitales innovantes. Grâce à un webdesign soigné, des templates modernes et une gestion efficace de l'e-réputation, je m'assure que votre site, qu'il soit destiné à une entreprise web, soit parfaitement référencé sur Google conformément aux exigences du web-marketing et de la stratégie marketing inbound.
  - id: 3
    icon: fa-lock
    question: En quoi consiste l'assistanat virtuel et comment peut-il m'aider ?
    answer: L'assistanat virtuel inclut la gestion de projets web, la coordination avec nos consultants et la gestion des campagnes emailing, en optimisant le développement du site et la conception de sites via des solutions digitales innovantes. Cette approche renforce la communication web et l'expérience utilisateur, aidant votre entreprise web à créer un site internet professionnel et attractif.
  - id: 4
    icon: fa-lock
    question: Quelle est votre approche pour la création de sites web ?
    answer: Je conçois des sites vitrines, e-commerce, intranet ou responsives, en utilisant des CMS performants comme WordPress, Drupal, Magento, Prestashop et Joomla. Chaque projet, qu'il s'agisse de la création de site, de site internet ou de la conception de sites, est réalisé avec une attention particulière à l'expérience utilisateur, au design responsive, à la création graphique et au nom de domaine, par un concepteur de site Web expert. La refonte ou le développement du site est pensé pour offrir une navigation fluide et une identité visuelle unique, que ce soit pour créer un site internet ou réaliser un nouveau site attractif.
  - id: 5
    icon: fa-lock
    question: Quels outils utilisez-vous pour le SEO et le marketing digital ?
    answer: J’utilise des outils performants tels que Google Analytics, Google Search Console et des plateformes publicitaires comme Google Ads pour piloter une stratégie marketing et web-marketing efficace. Ces outils, couplés à des solutions digitales innovantes et à l'optimisation du référencement d'un site, garantissent une visibilité accrue pour votre site internet, que ce soit pour une entreprise web.
  - id: 6
    icon: fa-lock
    question: Avez-vous une expérience en gestion d'équipe ?
    answer: Oui, en tant que chef de projet et prestataire web, je coordonne une équipe de consultants spécialisés en SEO, rédaction de contenu, référencement payant, webdesign et développement du site. Grâce à des solutions digitales et à des supports de communication modernes, nous assurons la création graphique, la conception de site et le développement d'un site web de qualité, garantissant une expérience utilisateur optimale et la réalisation d'un site attractif pour votre entreprise web.
  - id: 7
    icon: fa-lock
    question: Quels types de projets avez-vous gérés ?
    answer: J'ai géré divers projets, allant de la création de site, la création de site internet et la conception de sites, à la refonte et au développement d'un site web, sans oublier la réalisation d'un site internet professionnel. Mes projets incluent également la mise en œuvre de stratégies de communication digitale et marketing inbound, optimisant le référencement d'un site et l'expérience utilisateur, afin d'attirer de nouveaux clients et renforcer l'image d'une entreprise web.
  - id: 8
    icon: fa-lock
    question: Quels sont vos tarifs pour les services SEO et marketing digital ?
    answer: "Je propose des forfaits adaptés à chaque besoin, que ce soit pour créer un site internet, réaliser un site web ou développer un site, ainsi que pour le référencement d'un site et la gestion de campagnes publicitaires. Mon approche intègre des solutions de community management, des stratégies inbound et des outils digitaux, garantissant l'optimisation du développement du site et de l'expérience utilisateur. Pour découvrir nos réalisations et obtenir un devis personnalisé pour votre nouveau site, n'hésitez pas à me contacter."
  - id: 9
    icon: fa-lock
    question: Pourquoi devrais-je choisir vos services ?
    answer: Vous devriez choisir mes services en raison de mon expertise approfondie en SEO, webmarketing et en conception de site Web, associée à une stratégie digitale globale. En tant que freelance et concepteur de site, et en collaboration avec des agences digitales, agences de création et agences internet, j'offre des solutions web sur mesure pour créer un site internet, refondre ou développer un site. Ma méthode intègre des techniques inbound, un design responsive et l'utilisation de templates modernes, garantissant une expérience utilisateur optimale et un retour sur investissement pour votre entreprise web.
  - id: 10
    icon: fa-lock
    question: Comment puis-je vous contacter ?
    answer: Vous pouvez me joindre via le <a href=\"/contact\">formulaire de contact</a>, par email ou téléphone. En tant que prestataire web et créateur de site, je suis disponible pour collaborer en télétravail ou en présentiel, et pour discuter de la création de site internet, de la réalisation d'un site internet ou de la refonte et du développement du site, afin d'améliorer votre présence sur le Web et d'optimiser votre internet création.
#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: miarofandresena@gmail.com
contact-info : f/xblryjqd
