---
#-------------------------------
# General Site Settings

title: Miaro
logo: assets/images/favicon.png
author: Miaro Fandresena
description: Boostez votre visibilité en ligne avec Miaro Fandresena, spécialiste en SEO, marketing digital.
email: miarofandresena@gmail.com
phone: +261 343388363
address: Sabotsy Namehana, Antananarivo, Madagascar
copyright: Copyright &copy; Miaro Fandresena 2025

menu:
  - { name: A propos, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
#  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! Je suis <br> Miaro Fandresena <br> Specialiste SEO

social:
  - { icon: "ti-facebook", link: "https://web.facebook.com/miarofandresena.rafanomezaniavo/" }
  - { icon: "ti-github", link: "https://github.com/miarofandresena/" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/miaro-fandresena-rafanomezaniavo-574208161/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Passionné par le Web, j'ai consacré les quatre dernières années à me spécialiser dans le référencement naturel (SEO) et la création de site internet. En tant que freelance, j'excelle dans la gestion de contenu et l’optimisation de votre site internet, que ce soit pour des agences de communication, des agences de communication digitale, des agences web ou des entreprises souhaitant améliorer leur visibilité en ligne. Que ce soit pour la création de site, la refonte du site ou la réalisation d un site, mon expertise en web-design, stratégie de communication et stratégie marketing me permet de proposer des solutions optimisées, alliant ergonomie, graphisme et supports de communication digitaux. Je transforme vos idées en nos réalisations concrètes sur le Web, que ce soit pour un site vitrine, un intranet, un Ecommerce, ou une application mobile adaptée aux tablettes, avec un nom de domaine soigné et un design innovant.

blurb-btn-link: "/about"
blurb-btn-name: Apprendre plus sur moi

# About Page

# Work Process Section
# work-process:
#   - title: "Research and Plan"
#     icon: "assets/images/icons/plan.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Design and Develop"
#     icon: "assets/images/icons/design.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Deliver"
#     icon: "assets/images/icons/print.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# # My Team Section
# team:
#   - title: "Jack Schenziwe"
#     image: "assets/images/team/member-1.png"
#     designation: "Project Manager"

#   - title: "Julias Carlie"
#     image: "assets/images/team/member-2.png"
#     designation: "Web Developer"

#   - title: "John Doe"
#     image: "assets/images/team/member-3.png"
#     designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: SEO, color: "#fdb157", value: "90%" }
  - { name: WordPress, color: "#9473e6", value: "80%" }
  - { name: Marketing Digital, color: "#bdecf6", value: "50%" }
  - { name: Gestion de Projet Web, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-1.png",
      date: "Février 2024 - Maintenant",
      organization: "A mon compte",
    }
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-2.png",
      date: "Septembre 2020 - Février 2024",
      organization: "X-Com Agency",
    }
  - {
      name: "Développeur Web",
      icon: "icon-3.png",
      date: "Décembre 2019 - Janvier 2020",
      organization: "Cubicom",
    }
  - {
      name: "Développeur Web",
      icon: "icon-1.png",
      date: "Janvier 2019 - Juillet 2020",
      organization: "Wiclick",
    }
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Licence en Informatique,
      date: "2019",
      organization: "UPH",
    }
  - {
      name: "Diplôme de Technicien Supérieur",
      date: "2016",
      organization: "ISIME",
    }
  - {
      name: "Baccalauréat Série A2",
      date: "2015",
      organization: "LP Idéal",
    }
#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: "Optimisation SEO Avancée",
      icon: ti-palette,
      description: "Maximisez la visibilité de votre site internet sur les moteurs de recherche grâce à des stratégies de référencement naturel personnalisées. Notre agence web vous aide à améliorer votre notoriété en ligne et à optimiser le référencement de votre site, que ce soit pour la création de site, la création de site internet ou la création de sites internet. Nous veillons à ce que chaque création de site web soit conçue avec une ergonomie soignée, un design responsive et une réactivité optimale sur le Web. Ainsi, nous attirons de nouveaux clients, renforçons votre stratégie de communication et assurons la réussite de votre présence digitale à long terme. 🚀",
      link: /seo,
      active: , # Add true to select section
    }
  - {
      name: "Gestion de Marketing Digital",
      icon: ti-vector,
      description: "Déployez une stratégie digitale performante en combinant SEO, web-marketing, et référencement payant (Google Ads, Facebook Ads). Notre agence de communication digitale vous accompagne dans l'optimisation de votre communication web, en élaborant une stratégie de communication et une stratégie marketing inbound. Nous mobilisons nos consultants et exploitons divers supports de communication digitaux pour vous aider à atteindre vos objectifs et toucher de nouveaux publics. Forte de notre expérience en tant qu'agence de communication, nous vous proposons des solutions adaptées aux enjeux digitaux actuels.",
      link: /marketing,
      active: true, # Add true to select section
    }
  - {
      name: "Développement de Sites Web",
      icon: ti-panel,
      description: "Créez un site internet vitrine, e-commerce, intranet ou responsive, performant et sécurisé. Spécialisés en webdesign, nous assurons la création de site internet optimisé. Optez pour 'Créer un site' qui reflète votre identité digitale. Nos projets incluent des fonctionnalités Ecommerce, intranet, applications mobiles et tablettes, avec un nom de domaine adapté. En tant qu'agence de communication web, nous réalisons des sites avec des solutions Magento et Joomla, et nous sommes spécialisés dans la création de projets digitaux innovants. Nous proposons également la refonte du site pour moderniser votre image et garantir une ergonomie optimale.",
      link: /web,
      active: , # Add true to select section
    }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-4.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Référencement Naturel", type: "referencement" }
  - { title: "Marketing Digital", type: "maketing" }
  - { title: "Gestion de site web", type: "web" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"
      - type: "web"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-6.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"

  - image: "assets/images/portfolio/item-8.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"
      - type: "referencement"

  - image: "assets/images/portfolio/item-7.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
faq-items:
  - id: 1
    icon: fa-question-circle
    question: Quels services proposez-vous ?
    answer: J'offre des services en SEO, webmarketing et stratégie digitale, incluant la création de site, la création de site internet et la création de sites internet, ainsi que la refonte du site et l'optimisation de votre site internet sur le Web. Mon expertise s'étend à la gestion de contenu, au développement web, à l'identité visuelle et à la communication, en collaboration avec des agences de communication et des agences de communication digitale, et ce, en élaborant une stratégie de communication efficace et en garantissant une ergonomie et un graphisme optimisés.
  - id: 2
    icon: fa-truck
    question: Comment pouvez-vous améliorer la visibilité de mon site sur Google ?
    answer: J'applique une stratégie de référencement naturel et payant optimisée pour améliorer la visibilité de votre site internet sur Google. En combinant l'optimisation des mots-clés, un webdesign soigné, la gestion de l’e-réputation et la création de backlinks, ainsi que la mise en place de campagnes Google AdWords, je m'assure que votre site soit réactif et conforme aux exigences du web-marketing et de la stratégie marketing inbound.
  - id: 3
    icon: fa-lock
    question: En quoi consiste l'assistanat virtuel et comment peut-il m'aider ?
    answer: L'assistanat virtuel inclut la gestion de projets web, la coordination avec nos consultants, la gestion des campagnes emailing et l’optimisation des stratégies d’e-marketing. Cela permet de renforcer la communication web via divers supports de communication digitaux et d’améliorer la présence digitale d’une entreprise sur le Web.
  - id: 4
    icon: fa-lock
    question: Quelle est votre approche pour la création de sites web ?
    answer: Je conçois des sites vitrines, e-commerce, intranet ou adaptés aux applications mobiles et tablettes, en utilisant des CMS performants tels que WordPress, Drupal, Magento et Joomla. Chaque projet, qu'il s'agisse de la création de site, de la création de site internet, de la création de sites internet ou de la création de site web, est réalisé sur le site avec une attention particulière à l'ergonomie, au nom de domaine et au design apporté par un designer expert. Ainsi, la refonte du site ou la réalisation d un site est toujours pensée pour offrir une navigation fluide et une identité visuelle unique.
  - id: 5
    icon: fa-lock
    question: Quels outils utilisez-vous pour le SEO et le marketing digital ?
    answer: J’utilise des outils performants tels que Google Analytics, Google Search Console, et des plateformes de publicité comme Google Ads, afin de piloter une stratégie marketing et web-marketing efficace. Ces outils, associés à une approche inbound, permettent d’optimiser le référencement et la visibilité de votre site internet sur le Web.
  - id: 6
    icon: fa-lock
    question: Avez-vous une expérience en gestion d'équipe ?
    answer: Oui, en tant que chef de projet, je coordonne une équipe de consultants spécialisés en SEO, rédaction de contenu, référencement payant, webdesign, et développement web. Grâce à une communication structurée et à l'utilisation de supports de communication digitaux, je m'assure que chaque projet, qu'il s'agisse de la création ou de la refonte du site, soit mené avec réactivité et efficacité.
  - id: 7
    icon: fa-lock
    question: Quels types de projets avez-vous gérés ?
    answer: J'ai travaillé sur divers projets incluant la création de site, la création de site internet et la création de sites internet, ainsi que sur la refonte du site et la réalisation d un site. Mes projets englobent également l'élaboration de stratégies de communication digitale et de stratégie marketing, visant à optimiser le référencement naturel et à attirer de nouveaux clients via des campagnes d’e-mailing et d’e-marketing.
  - id: 8
    icon: fa-lock
    question: Quels sont vos tarifs pour les services SEO et marketing digital ?
    answer: "Je propose des forfaits adaptés à chaque besoin, que ce soit pour la création de site, la création de site internet ou la réalisation d un site, ainsi que pour le référencement et la gestion de campagnes publicitaires dans le cadre d'une stratégie marketing complète. Mon approche intègre également des solutions de community management et de web-marketing pour garantir des résultats optimisés. Pour découvrir nos réalisations et obtenir un devis personnalisé, n'hésitez pas à me contacter."
  - id: 9
    icon: fa-lock
    question: Pourquoi devrais-je choisir vos services ?
    answer: Vous devriez choisir mes services en raison de mon expertise approfondie en SEO et webmarketing, associée à une stratégie digitale globale. En tant que freelance, et en collaboration avec des agences de communication, j'offre des solutions optimisées pour la création de site, la refonte du site et la réalisation d un site. Ma méthode intègre une stratégie de communication efficace, des techniques inbound et le travail de consultants expérimentés, garantissant une présence digitale percutante et un retour sur investissement optimal.
  - id: 10
    icon: fa-lock
    question: Comment puis-je vous contacter ?
    answer: Vous pouvez me joindre via le <a href=\"/contact\">formulaire de contact</a>, par email ou téléphone. Quel que soit le support de communication choisi, je suis disponible pour collaborer en télétravail ou en présentiel, et pour discuter de la création ou de la refonte du site, afin d'améliorer votre présence sur le Web.
#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: miarofandresena@gmail.com
contact-info : f/xblryjqd
