---
#-------------------------------
# General Site Settings

title: Miaro
logo: assets/images/favicon.png
author: Miaro Fandresena
description: Miaro Fandresena Rafanomezaniavo Website
email: miarofandresena@gmail.com
phone: +261 343388363
address: Sabotsy Namehana, Antananarivo, Madagascar
copyright: Copyright &copy; 2024

menu:
  - { name: A propos, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! Je suis <br> Miaro Fandresena <br> Specialiste SEO

social:
  - { icon: "ti-facebook", link: "https://web.facebook.com/miarofandresena.rafanomezaniavo/" }
  - { icon: "ti-github", link: "https://github.com/miarofandresena/" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/miaro-fandresena-rafanomezaniavo-574208161/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Passionné par le Web, j'ai consacré les quatre dernières années à me spécialiser dans le référencement naturel (SEO), où j'excelle dans la gestion de sites, de réseaux de sites, et de sites d'affiliation.

blurb-btn-link: "/about"
blurb-btn-name: Apprendre plus sur moi

# About Page

# Work Process Section
# work-process:
#   - title: "Research and Plan"
#     icon: "assets/images/icons/plan.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Design and Develop"
#     icon: "assets/images/icons/design.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Deliver"
#     icon: "assets/images/icons/print.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# # My Team Section
# team:
#   - title: "Jack Schenziwe"
#     image: "assets/images/team/member-1.png"
#     designation: "Project Manager"

#   - title: "Julias Carlie"
#     image: "assets/images/team/member-2.png"
#     designation: "Web Developer"

#   - title: "John Doe"
#     image: "assets/images/team/member-3.png"
#     designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: SEO, color: "#fdb157", value: "90%" }
  - { name: WordPress, color: "#9473e6", value: "80%" }
  - { name: Marketing Digital, color: "#bdecf6", value: "50%" }
  - { name: Gestion de Projet Web, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-1.png",
      date: "Février 2024 - Maintenant",
      organization: "A mon compte",
    }
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-2.png",
      date: "Septembre 2020 - Février 2024",
      organization: "X-Com Agency",
    }
  - {
      name: "Développeur Web",
      icon: "icon-3.png",
      date: "Décembre 2019 - Janvier 2020",
      organization: "Cubicom",
    }
  - {
      name: "Développeur Web",
      icon: "icon-1.png",
      date: "Janvier 2019 - Juillet 2020",
      organization: "Wiclick",
    }
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Licence en Informatique,
      date: "2019",
      organization: "UPH",
    }
  - {
      name: "Diplôme de Technicien Supérieur",
      date: "2016",
      organization: "ISIME",
    }
  - {
      name: "Baccalauréat Série A2",
      date: "2015",
      organization: "LP Idéal",
    }
#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: "Optimisation SEO Avancée",
      icon: ti-palette,
      description: "Maximisez la visibilité de votre site web grâce à des stratégies de référencement naturel personnalisées, conçues pour améliorer votre classement sur les moteurs de recherche et attirer un trafic qualifié.",
      active: ,# Add true to select section
    }
  - {
      name: "Gestion de Marketing Digital",
      icon: ti-vector,
      description: "Boostez votre présence en ligne avec des campagnes de marketing digital efficaces, incluant le marketing d'affiliation et d'influence, pour augmenter vos ventes et fidéliser vos clients.",
      active: true, # Add true to select section
    }
  - {
      name: Développement et Maintenance de Sites Web,
      icon: ti-panel,
      description: "Créez et maintenez des sites web performants et sécurisés grâce à nos services de développement web sur mesure, en utilisant les dernières technologies pour garantir une expérience utilisateur optimale.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-4.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Référencement Naturel", type: "referencement" }
  - { title: "Marketing Digital", type: "maketing" }
  - { title: "Gestion de site web", type: "web" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"
      - type: "web"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-6.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"

  - image: "assets/images/portfolio/item-8.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"
      - type: "referencement"

  - image: "assets/images/portfolio/item-7.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
faq-items:
  - id: 1
    icon: fa-question-circle
    question: Quels services proposez-vous ?
    answer: Je suis spécialisé en SEO, assistanat virtuel, gestion de projets numériques, et développement web. Je vous aide à optimiser votre présence en ligne, à améliorer votre visibilité sur Google, et à assurer un suivi client fluide. Mon expertise couvre également la création de contenu optimisé pour le SEO et la gestion de sites e-commerce.
  - id: 2
    icon: fa-truck
    question: Comment pouvez-vous améliorer la visibilité de mon site sur Google ?
    answer: Grâce à des stratégies SEO avancées, j'optimise votre site en fonction des meilleures pratiques de référencement naturel. Cela inclut l'optimisation des mots-clés, la création de backlinks de qualité, et l'amélioration du contenu pour répondre aux exigences des moteurs de recherche, augmentant ainsi votre classement sur Google.
  - id: 3
    icon: fa-lock
    question: Qu'est-ce que l'assistanat virtuel et en quoi cela peut-il m'aider ?
    answer: L'assistanat virtuel inclut la gestion administrative à distance, comme la gestion des emails, l'organisation d'agendas, et le suivi des tâches. Cela vous permet de vous concentrer sur des activités à plus forte valeur ajoutée pendant que je prends en charge les aspects administratifs, assurant une productivité accrue et une meilleure gestion de votre temps.
  - id: 4
    icon: fa-lock
    question: Quelle est votre approche pour la création de sites web ?
    answer: Je conçois des sites WordPress sur mesure, en développant des designs modernes et intuitifs qui améliorent l'expérience utilisateur. Mon objectif est de créer des sites performants et optimisés pour le SEO, tout en restant faciles à gérer pour les propriétaires de sites.
  - id: 5
    icon: fa-lock
    question: Quels outils utilisez-vous pour gérer le SEO et les campagnes marketing ?
    answer: J'utilise une combinaison d'outils performants tels que Google Analytics, Google Search Console, et Ubersuggest pour suivre les performances des sites et analyser les résultats des campagnes SEO. Je suis également familiarisé avec les plateformes publicitaires comme Google Ads et Facebook Ads pour maximiser la visibilité de vos campagnes marketing.
  - id: 6
    icon: fa-lock
    question: Quelle est votre expérience dans la gestion d'une équipe ?
    answer: Actuellement, je supervise une équipe de 5 personnes, chacune spécialisée dans des domaines comme la rédaction SEO, l'acquisition de backlinks, et la gestion des sites e-commerce. Mon rôle consiste à coordonner les efforts de l'équipe pour atteindre les objectifs fixés tout en respectant les délais.
  - id: 7
    icon: fa-lock
    question: Quels types de projets avez-vous gérés ?
    answer: J'ai géré divers projets, allant de la création et refonte de sites WordPress à la gestion de campagnes de marketing digital pour des entreprises. Mon expertise couvre la planification, la gestion des ressources, et l'assurance qualité tout au long du processus pour garantir des résultats optimaux.
  - id: 8
    icon: fa-lock
    question: Quels sont vos tarifs pour les services SEO et assistanat virtuel ?
    answer: Mes tarifs varient en fonction des besoins spécifiques de chaque projet. Je propose des forfaits personnalisés adaptés à vos objectifs et à votre budget. N'hésitez pas à me contacter pour discuter d'une solution sur mesure.
  - id: 9
    icon: fa-lock
    question: Pourquoi devrais-je faire appel à vos services ?
    answer: Avec plusieurs années d'expérience en SEO, développement web, et gestion de projets, je propose des solutions complètes pour améliorer votre présence en ligne et vous aider à atteindre vos objectifs. Mon approche est axée sur la collaboration, la transparence, et des résultats mesurables.
  - id: 10
    icon: fa-lock
    question: Comment puis-je vous contacter ?
    answer: Vous pouvez me contacter via le <a href="/contact">formulaire de contact</a> sur ce site, ou directement par email ou téléphone. Je suis disponible en télétravail ou en présentiel, selon vos besoins.

#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: miarofandresena@gmail.com
contact-info : f/xblryjqd
