---
#-------------------------------
# General Site Settings

title: Miaro
logo:
author: Miaro Fandresena
description: Miaro Fandresena Rafanomezaniavo Website
email: miarofandresena@gmail.com
phone: +261 343388363
address: Sabotsy Namehana, Antananarivo, Madagascar
copyright: Copyright &copy; 2024

menu:
  - { name: A propos, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! Je suis <br> Miaro Fandresena <br> Specialiste SEO

social:
  - { icon: "ti-facebook", link: "https://web.facebook.com/miarofandresena.rafanomezaniavo/" }
  - { icon: "ti-github", link: "https://github.com/miarofandresena/" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/miaro-fandresena-rafanomezaniavo-574208161/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Passionné par le Web, j'ai consacré les quatre dernières années à me spécialiser dans le référencement naturel (SEO), où j'excelle dans la gestion de sites, de réseaux de sites, et de sites d'affiliation.

blurb-btn-link: "/about"
blurb-btn-name: Apprendre plus sur moi

# About Page

# Work Process Section
# work-process:
#   - title: "Research and Plan"
#     icon: "assets/images/icons/plan.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Design and Develop"
#     icon: "assets/images/icons/design.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Deliver"
#     icon: "assets/images/icons/print.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# # My Team Section
# team:
#   - title: "Jack Schenziwe"
#     image: "assets/images/team/member-1.png"
#     designation: "Project Manager"

#   - title: "Julias Carlie"
#     image: "assets/images/team/member-2.png"
#     designation: "Web Developer"

#   - title: "John Doe"
#     image: "assets/images/team/member-3.png"
#     designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: SEO, color: "#fdb157", value: "90%" }
  - { name: WordPress, color: "#9473e6", value: "80%" }
  - { name: Marketing Digital, color: "#bdecf6", value: "50%" }
  - { name: Gestion de Projet Web, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-1.png",
      date: "Février 2024 - Maintenant",
      organization: "A mon compte",
    }
  - {
      name: "SEO & Intégrateur web",
      icon: "icon-2.png",
      date: "Septembre 2020 - Février 2024",
      organization: "X-Com Agency",
    }
  - {
      name: "Développeur Web",
      icon: "icon-3.png",
      date: "Décembre 2019 - Janvier 2020",
      organization: "Cubicom",
    }
  - {
      name: "Développeur Web",
      icon: "icon-1.png",
      date: "Janvier 2019 - Juillet 2020",
      organization: "Wiclick",
    }
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Licence en Informatique,
      date: "2019",
      organization: "UPH",
    }
  - {
      name: "Diplôme de Technicien Supérieur",
      date: "2016",
      organization: "ISIME",
    }
  - {
      name: "Baccalauréat Série A2",
      date: "2015",
      organization: "LP Idéal",
    }
#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: "Optimisation SEO Avancée",
      icon: ti-palette,
      description: "Maximisez la visibilité de votre site web grâce à des stratégies de référencement naturel personnalisées, conçues pour améliorer votre classement sur les moteurs de recherche et attirer un trafic qualifié.",
      active: ,# Add true to select section
    }
  - {
      name: "Gestion de Marketing Digital",
      icon: ti-vector,
      description: "Boostez votre présence en ligne avec des campagnes de marketing digital efficaces, incluant le marketing d'affiliation et d'influence, pour augmenter vos ventes et fidéliser vos clients.",
      active: true, # Add true to select section
    }
  - {
      name: Développement et Maintenance de Sites Web,
      icon: ti-panel,
      description: "Créez et maintenez des sites web performants et sécurisés grâce à nos services de développement web sur mesure, en utilisant les dernières technologies pour garantir une expérience utilisateur optimale.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-4.jpg"
    url: "#"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Référencement Naturel", type: "referencement" }
  - { title: "Marketing Digital", type: "maketing" }
  - { title: "Gestion de site web", type: "web" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"
      - type: "web"

  - image: "assets/images/portfolio/item-2.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-6.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"

  - image: "assets/images/portfolio/item-8.jpg"
    url: "#"
    portfolio-type:
      - type: "referencement"

  - image: "assets/images/portfolio/item-5.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

  - image: "assets/images/portfolio/item-1.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"

  - image: "assets/images/portfolio/item-3.jpg"
    url: "#"
    portfolio-type:
      - type: "marketing"
      - type: "web"
      - type: "referencement"

  - image: "assets/images/portfolio/item-7.jpg"
    url: "#"
    portfolio-type:
      - type: "web"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: miarofandresena@gmail.com
